image: golang:1.12

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - env DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -yq install libxml2-dev
    - tools/build-linux.sh
  artifacts:
    paths:
      - out/bin/linux/amd64/gurl
      - out/bin/linux/amd64/gurlfmt

test:
  stage: test
  script:
    - env DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -yq install libxml2-dev
    - tools/coverage.sh
  coverage: '/total:\s+\(statements\)\s+(\d+.\d+%)/'
  artifacts:
    paths:
      - out/coverage.html

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mkdir -p public/coverage
    - cp out/coverage.html public/coverage/index.html
  artifacts:
    paths:
      - public
