image: golang:1.12

build:
  script:
    - tools/build-all.sh
  artifacts:
    paths:
      - build/bin/darwin/amd64/gurl
      - build/bin/linux/amd64/gurl
      - build/bin/windows/amd64/gurl.exe

test:
  script:
    - tools/coverage.sh
  artifacts:
    paths:
      - build/coverage.html

pages:
  dependencies:
    - test
  script:
    - mkdir -p public
    - cp tools/coverage.html public/
  artifacts:
    paths:
      - public
