image: golang:1.12

build:
  script:
    - tools/buid.sh
  artifacts:
    paths:
      - build/gurl

test:
  script:
    - tools/coverage.sh
  artifacts:
    paths:
      - build/coverage.html

pages:
  dependencies:
    - test
  script:
    - mkdir -p public
    - cp tools/coverage.html public/
  artifacts:
    paths:
      - public
