image: golang:1.12

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - env DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -yq install libxml2-dev
    - tools/build-all.sh
  artifacts:
    paths:
      - out/bin/linux/amd64/gurl

test:
  stage: test
  script:
    - env DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -yq install libxml2-dev
    - tools/coverage.sh
  artifacts:
    paths:
      - out/coverage.html

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mkdir -p public
    - cp tools/coverage.html public/
  artifacts:
    paths:
      - public
