language: go

go:
  - "1.12"

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxml2-dev

script:
  - tools/build-darwin.sh
  - tools/coverage.sh


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  verbose: true
  local_dir: out/