language: go

go:
  - "1.12"

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxml2-dev

script:
  - tools/build-linux.sh
  - tools/coverage.sh
  - tools/coverage-travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  verbose: true
  local_dir: out/
  repo: jcamiel/jcamiel.github.io
  target_branch: master