FROM alpine

RUN apk add build-base
COPY clib/libxml2-2.9.9.tar.gz /tmp/
WORKDIR /tmp
RUN tar xvzf libxml2-2.9.9.tar.gz
WORKDIR /tmp/libxml2-2.9.9
RUN ./configure --prefix=/opt/local --enable-static --disable-shared
RUN make
RUN make install
